server:
  port: 8091
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://服务器内网地址:8123
          predicates:
            - Path=/api/**
      default-filters:
        - AddResponseHeader=source,madou
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://服务器内网地址:8848


