
server:
  port: 8123
  servlet:
    context-path: /api
geapi:
  client:
    access-key: madou
    secret-key: madou123
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interface_api
    username: root
    password: 123456
