
server:
  port: 8123
  servlet:
    context-path: /api
geapi:
  client:
    access-key: madou
    secret-key: madou123
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.5.119:3306/interface_api
    username: ge_api1
    password: 789159357Zj
